apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.3.248.129  # Modify nfs-server IP
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-store-claim # See to that this match PVC name in torchserve
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
